### ISSUE TITLE
Documentation and help

### ISSUE THREAD

**Issue by Sanjay-Swain** [ErrorDAR32/VSSM#2]
Hello, 
I found this repository while scrolling randomly on GitHub and as a beginner (having not much coding experience and young, I am yet at high school) I like this project as an opportunity to learn and help you. So I wanted to to contribute to this project but can't actually know what and how the program works. The documentation is good but I have no idea how sales system works so it would be great if you can say what it does in brief. I don't have much experience and I have much to learn but I guess I can help you a little here.
Thanks

**Comment by ErrorDAR32** [comment]
Hi! thank you for passing by and sticking around, i actually haven't worked on documentation that much because i really didn't thought that someone would actually try to collaborate! in fact, the current docs are a bit outdated and were mostly done so i didn't forget some ideas.
As for how "good for business" this may be, i actually don't know that much about how a business program must work, this is mostly to figure things out while i go. I will update the documentation and also respond to you how this is supposed to work.

right now the program is just a back-end, everything must be CLI, right now i'm working on the client and product manipulation commands (in commands.py) and after that work on a parser to parse those commands from a future "input() loop" in main.py
if you see the commits i was actually working on serialization first, but i decided it'll be better to left that to the end.

**Comment by Sanjay-Swain** [comment]
Hello there,
I, as a newbie to this programming stuff, actually like this project. I have forked this repository and while messing around I got a pretty good idea what you want to do with this program. There are few things however I found that needs to be changed but for now it will work. And I am going to work on this project now so you can count me in for contributing to the project. I found this a good opportunity to actually put into use what I know and learn new stuff (and hope you will too).
Thanks.

**Comment by ErrorDAR32** [comment]
Great! any doubts you have you can just ask me, as a newbie as myself I'm actually really happy about getting help.
Looking Forward to work with you!

**Comment by Sanjay-Swain** [comment]
Hi! okay then I found a file `testarea1.py`. This has a class `FileHandeler` , which I guess, for now is just for testing how to manipulate XML files to store the data. While I think we actually need the class for handling files but using python builtin file management tool can work using `open()` methods but will be a lot tidious but instead we can use a XML library for handling and storing data like I found this [basic tutorial](https://www.geeksforgeeks.org/reading-and-writing-xml-files-in-python/) for that. It explain how to read and write XML file using a library (which comes built-in with python for me) called `ElementTree`. What do you think about it? I am going create a new branch and add my modifications there after some time. Please tell me that will work or not.

**Comment by ErrorDAR32** [comment]
oh yeah, that was and old attemp at the archive implementation that just stuck there, it actually is deprecated, as for the XML part, i think it is a good idea, i was thinking of doing it by hand (to learn and stuff) but i now think the time saved is more worth it, and also i dont know that much about parsers.
also, about file handler, it was suposed to manage the archive, and load/save files into it. but im first working on the functional part first, and leaving serialization for last.

**Comment by Sanjay-Swain** [comment]
Hi! After playing around a bit with XML files I got how to modify/read XML file.
`<VSSM>
    <client><data id="0" name="Mike" /><data id="1" name="Sanjay" /></client>
</VSSM>`
This is how the XML file will look like after two insertion of client data. I am trying to keep things simple.

So I am actually thinking like this:
- when the code is run first time the program will create a XML file having the following structure:
> `<VSSM>
     <client>......</client>
     <product>......</product>
     </VSSM>`
- And in between those '....' later the data (client information, product information, etc...) will be added.

This is how I am thinking to start things. I don't know much so I am yet learning and this is not implemented in the code (yet!) these are just test run. And I am kind of learning things on the go. So it may take some time.

**Comment by ErrorDAR32** [comment]
I actually like the idea, looks good enough for me and is mostly what i was thinking. my old archive concept was basically simulating a file system within a file, just for the fun of it, but this is simple and better tbh. you can make a pull request when you have it ready
I have to say, is pretty strange to have someone helping me!
And beforehand, sorry if i don't respond within 24 hours or so, university got me pinned down on projects and stuff.
as far as my "progress" goes, im actually updating the documentation right now

**Comment by ErrorDAR32** [comment]
on another topic, we should use another medium of communication as this is rather inconvenient for me. it could be discord for example, you can also propose one

**Comment by ErrorDAR32** [comment]
On the XML structure, i would prefer something like:

```
<VSSM>
    <clients>
        <client id =0>
            <name>Luis </name>
           ...
        </client>
        <client id=1>
            <name>Juan</name>
            ...
        </client>
    </clients>
    <products>
        <product id= 2>
        ...
       </product>
    </products>
</VSSM>
````
space really isn't a concern, i am most concerned on the "backend" being as CPU non intensive as possible. as for the indentation, it is  only necesary if we want to keep the archive human readable, which we may want to.

**Comment by ErrorDAR32** [comment]
also, try to not use """much""" ram, that is only load things that you need, like a single client entry instead of the whole archive for example.but dont be as paranoid as me

**Comment by Sanjay-Swain** [comment]
Yeah you are right we can communicate through discord. You can create a public server and just add the link in the documentation. It will be good enough. And it's okay about late response I also have school so I can feel what you want to say there : ).

**Comment by ErrorDAR32** [comment]
Great, ill be doing a push with the link in a couple of minutes!

**Comment by ErrorDAR32** [comment]
the link is up now! go join!
